project_name: AnyAppStart
builds:
  - main: ./cmd/AnyAppStart/
    binary: AnyAppStart
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"

nfpms:
  - id: systemd
    formats:
    - deb
    - rpm
    maintainer: aceberg <aceberg_a@proton.me>
    description: Start/Stop Docker, Systemd and other apps
    homepage: https://github.com/aceberg/AnyAppStart
    license: MIT
    section: utils
    contents:
    - src: ./configs/AnyAppStart.service
      dst: /lib/systemd/system/AnyAppStart.service
    - src: ./configs/AnyAppStart@.service
      dst: /lib/systemd/system/AnyAppStart@.service
    scripts:
      postinstall: ./configs/postinstall.sh

  - id: alpine
    formats:
    - apk
    maintainer: aceberg <aceberg_a@proton.me>
    description: Start/Stop Docker, Systemd and other apps
    homepage: https://github.com/aceberg/AnyAppStart
    license: MIT
    section: utils

archives:
  - files:
    - LICENSE
    - src: ./configs/AnyAppStart.service
      dst: AnyAppStart.service
    - src: ./configs/AnyAppStart@.service
      dst: AnyAppStart@.service
    - src: ./configs/install.sh
      dst: install.sh
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"
